name: Build Hotel Management System

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted   # or windows-latest if using GitHub-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Solution
        working-directory: "HOTELMANGMENT SYSTEM"
        run: dotnet build "HOTELMANGMENT SYSTEM.sln" --configuration Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HotelManagement-Build
          path: "HOTELMANGMENT SYSTEM/bin/Release/**"
