name: Build Hotel Management System

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build Solution
        run: dotnet build "HOTELMANGMENT SYSTEM.sln" --configuration Release
        working-directory: "HOTELMANGMENT SYSTEM"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HotelManagement-Build
          path: "HOTELMANGMENT SYSTEM/bin/Release/**"
